[phases.setup]
apt_pkgs = ["build-essential", "curl"]
cmds = [
    "curl https://sh.rustup.rs -sSf | sh -s -- -y",
    "source $HOME/.cargo/env"
]

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT}"
