# Generated by Django 5.1.2 on 2024-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_commentdata_twitter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Created date of the comment', null=True),
        ),
    ]
