# Generated by Django 5.0.6 on 2024-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_billing_profile_current_plan_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/1.png', null=True, upload_to='avatars/'),
        ),
    ]
